### PR TITLE
Compile dll's for each commit

### PR DESCRIPTION
**Pull request by Macleykun**
Hello there!

I always wanted to contribute to OpenLRR/LRR somehow, and while i'm more a sysadmin/automater, i wanted to supply a way to make it easy for people to download the compiled dll's for each commit.

I can futher expand this to generate an official release (if you create a tag when pushing), including release notes and all.

Do you like this PR?
Thank you for making OpenLRR :)

### CODE REVIEW

**Comment by trigger-segfault** [comment]
This is great! Can you explain more about what happens when a commit is pushed? Where does the built dll go if its not (currently) going into a GitHub release?

Ideally, GitHub pre-releases should be created with new commits, so that proper releases (when things are most-stable and have proper change logs) can still stand out. Additionally, these releases should follow the same folder structure as full releases. So:
```
OpenLRR-<tag>.zip
  OpenLRR/
    openlrr.dll (from ./bin/openlrr.dll)
    OpenLRR.exe (from ./OpenLRR.exe)
    Data/**     (from ./data/**)
    Settings/** (from ./data/**)
```
(I'm not sure how wildcards will work in the Workflow, so `./data/**` may not be accurate.)

***

The debug builds are only necessary for debugging, so I'm not sure if they need to be included. But to include them you can just drop both `openlrr-d.dll` and `OpenLRR-d.exe` into the same folder as the release binaries.

**Comment by trigger-segfault** [comment]
Alright, I understand now. And I agree, using OpenLRR-Release.zip and OpenLRR-Debug.zip makes much more sense here.

For now I think I'm content with doing the official releases and writing changelogs purely by hand. But having the artifacts from commits also means I can skip the step of throwing the solution into a root folder under C:\\ to make a clean build, which is very handy.

One last thing. Maybe it would be better to relable `stable_build` to `release_build`. Although it might be more confusing with the ambiguity between that and GitHub releases, "stable" is definitely not a guarantee with each commit. What are your thoughts on this? Is "stable" commonly used in this context?

**Comment by Macleykun** [comment]
> Alright, I understand now. And I agree, using OpenLRR-Release.zip and OpenLRR-Debug.zip makes much more sense here.
> 
> For now I think I'm content with doing the official releases and writing changelogs purely by hand. But having the artifacts from commits also means I can skip the step of throwing the solution into a root folder under C:\ to make a clean build, which is very handy.
> 
> One last thing. Maybe it would be better to reliable `stable_build` to `release_build`. Although it might be more confusing with the ambiguity between that and GitHub releases, "stable" is not a guarantee with each commit. What are your thoughts on this? Is "stable" commonly used in this context?

For the release, I would suggest that I can make it so that if you push a tag, a draft with uploaded binaries is already set for you. So you only need to write the changelog and make it a new release. It's not much but it's honest work :).

I agree with renaming the job steps to the builds they make. I don't think stable is used at all in github actions as artefacts, because of that reason :).

I'll incorporate these changes tonight and we'll look from there what can be improved/changed.

**Comment by Macleykun** [comment]
I made some more progress and got the build to upload properly:
image
The Commits are automatically added, but you remove that stuff if you want, the release is in draft and nobody can see it except maintainers/owners.

I noticed that with packaging the order of files is different of what you normally do.

Your latest release has:
```
OpenLRR
  > Data
  > Settings
  > openlrr.dll
  > OpenLRR.exe
```

My automatic build has:
```
bin
  > openlrr.dll
data
  > Data
  > Settings
      > Shortcuts.cfg
OpenLRR.exe
```

Would you like the order to be the same as yours? I can make that happen easily by moving the files around before uploading the artefacts.

**Comment by Macleykun** [comment]
I used a different upload action and that one works way better, no autogenerate changelog and i could also use the correct versioning.
I'll go ahead and re-arrange the files to reflect yours aswell

**Comment by trigger-segfault** [comment]
Yes, everything should be in the same folder. And files under Settings/ and (uppercase) Data/ should be under their relative paths, just like is seen in official releases. This is so that users can unzip everything and run it without needing to move files (besides supplying the game asset and compatibility files).

If there are issues getting the paths right, then falling back to just uploading the dll is fine though.

Edit: Alright, thank you. :)

**Comment by Macleykun** [comment]
sorry, it took a little while but i think it's done, what you think?
https://github.com/Macleykun/OpenLRR/releases/tag/v0.8.0.15

The body is also empty of the draft release, so you can type right away :).

Any other suggestions/ideas?

**Comment by trigger-segfault** [comment]
It looks great! You've even got the `OpenLRR/` root folder for the prepared releases. :D

The only things left are addressing the two review notes I added at the beginning about changing the `on: push: paths:` to `src/openlrr/**` + `resources/**`. And changing it so only the the OpenLRR dll project is built by adding `/t:openlrr` after the solution name in the msbuild arguments.

Lastly, maybe rename the workflow file to `build_artifacts.yml`. I'm not a fan of spaces or ampersands in file names, even if its only GitHub that needs to see the file.

After that, everything should be ready to merge.

***

*(Today I learned "Artifact" is yet another word with different English and British spellings)*

**Comment by Macleykun** [comment]
> It looks great! You've even got the `OpenLRR/` root folder for the prepared releases. :D
> 
> The only things left are addressing the two review notes I added at the beginning about changing the `on: push: paths:` to `src/openlrr/**` + `resources/**`. And changing it so only the the OpenLRR dll project is built by adding `/t:openlrr` after the solution name in the msbuild arguments.
> 
> Lastly, maybe rename the workflow file to `build_artifacts.yml`. I'm not a fan of spaces or ampersands in file names, even if its only GitHub that needs to see the file.
> 
> After that, everything should be ready to merge.
> 
> _(Today I learned "Artifact" is yet another word with different English and British spellings)_

I don't see a review yet, have you clicked on comment/save? It might be that you made a review but that it isn't visable for the public yet (i had the same issue in another PR review)

I'll address those 3 things now :)

**Comment by Macleykun** [comment]
She’s ready :) I tried to squash but failed :p

**Comment by trigger-segfault** [comment]
I can squash when merging the PR, so it's all good. Thanks!

**Comment by Macleykun** [comment]
Enjoy! :D

**Pull request merged**
